// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/LexerParser.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class LexerParser {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Lexer=$fix(LexerParser.createTransducer());
      $line=7;
      Object Parser2=$fix(LexerParser.createAutomaton2());
      $line=8;
      Object Parser=$fix(LexerParser.createAutomaton());
      $line=9;
      Object stdin=$fix($invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)}));
      $line=10;
      System.out.println($message(new Object[]{"Desea usar el parser  que implementa directamente la gram\u00E1tica (1 para SI)"}));
      $line=11;
      String mode=null;
      mode=$defaultValue(String.class);
      $line=12;
      mode=$cast(String.class,$fix(((java.util.Scanner)stdin).nextLine()));
      $line=17;
      if ($opEqualY(((java.lang.String)mode).charAt($int(0)),'1')) {
        $line=19;
        GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,Parser));
        $line=20;
        LexerParser.testParser($cast(gold.structures.automaton.ITransducer.class,Lexer),$cast(gold.structures.automaton.IPushdownAutomaton.class,Parser));
      }
      else {
        $line=24;
        GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,Parser2));
        $line=26;
        LexerParser.testParser($cast(gold.structures.automaton.ITransducer.class,Lexer),$cast(gold.structures.automaton.IPushdownAutomaton.class,Parser2));
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"main",$line);
    }
  }
  public static Object testParser(ITransducer M, IPushdownAutomaton P) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=36;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=37;
      Object string=$fix("22");
      $line=38;
      while (true) {
        if (!($opGreatY($invokeMethod("length",string,new Object[]{}),1))) break;
        $line=39;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=40;
        System.out.println($message(new Object[]{"Digite la cadena de entrada:"}));
        $line=41;
        string=$fix($opAdditY(((java.util.Scanner)sc).nextLine()," "));
        $line=42;
        Object result=$fix(((gold.structures.automaton.ITransducer)M).acceptsString($cast(java.lang.String.class,string)));
        $line=43;
        Object tokenStream=$fix(((gold.structures.automaton.ITransducer)M).getOutputString());
        $line=44;
        System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY("Lexicamente, la cadena fue aceptada ",(($bool(result))?("aceptada"):("rechazada"))),". Resultado: "),tokenStream)}));
        $line=47;
        result=$fix(((gold.structures.automaton.IPushdownAutomaton)P).acceptsString($cast(java.lang.String.class,tokenStream)));
        $line=48;
        System.out.println($message(new Object[]{$opAdditY("Sint\u00E1cticamente, la cadena fue ",(($bool(result))?("aceptada"):("rechazada")))}));
      }
      $line=51;
      System.out.println($message(new Object[]{"Termino la ejecucion"}));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"testParser",$line);
    }
    return $result;
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=67;
      Object Terms=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=68;
      Object NonTerms=$fix(GCollections.asSet('E','L'));
      $line=69;
      Object Q=$fix(GCollections.asSet("I","q","F"));
      $line=70;
      Object \u03A3=$fix(Terms);
      $line=71;
      Object \u0393=$fix($opUnionY($opUnionY(Terms,NonTerms),GCollections.asSet('$')));
      $line=72;
      Object q_0=$fix("I");
      $line=73;
      Object F=$fix(GCollections.asSet("F"));
      $line=74;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=76;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","q",$cast(java.lang.String.class,"")),new Object[]{"$E"});
      $line=77;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","F",$cast(java.lang.String.class,"")),new Object[]{"$"});
      $line=79;
      for (Object $v1:GCollections.unmodifiableCollection(GCollections.asSet('(',')','+','*','v','n'))) {
        Object x=$v1;
        $line=80;
        $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,$opAdditY("",x))),new Object[]{$opAdditY("",x)});
      }
      $line=82;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E","v"});
      $line=83;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E","n"});
      $line=84;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E",")L+("});
      $line=85;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"E",")L*("});
      $line=86;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"L","E"});
      $line=87;
      $invokeMethod("changeTop",((gold.structures.automaton.GPushdownAutomaton)M).delta("q","q",$cast(java.lang.String.class,"")),new Object[]{"L","EL"});
      $line=88;
      $result=M;
      if (true) break $try;
      $line=89;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
  public static IPushdownAutomaton createAutomaton2() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=103;
      Object Terms=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=104;
      Object NonTerms=$fix(GCollections.asSet('E','L'));
      $line=105;
      Object Q=$fix(GCollections.asSet("I","F"));
      $line=106;
      Object \u03A3=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=107;
      Object \u0393=$fix(GCollections.asSet('1'));
      $line=108;
      Object q_0=$fix("I");
      $line=109;
      Object F=$fix(GCollections.asSet("F"));
      $line=110;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=112;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","I",$cast(java.lang.String.class,"(+")),new Object[]{"1"});
      $line=113;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","I",$cast(java.lang.String.class,"(*")),new Object[]{"1"});
      $line=114;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","F",$cast(java.lang.String.class,"v")),new Object[]{});
      $line=115;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","F",$cast(java.lang.String.class,"n")),new Object[]{});
      $line=116;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("F","F",$cast(java.lang.String.class,")")),new Object[]{"1"});
      $line=117;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("F","I",$cast(java.lang.String.class,"")),new Object[]{});
      $line=120;
      $result=M;
      if (true) break $try;
      $line=121;
      $rethrow(new RuntimeException("The function \"createAutomaton2()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"createAutomaton2",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=128;
      Object Q=$fix(GCollections.asSet("I","Id","p","pl","plu","plus","t","ti","tim","time","times","Num","Err"));
      $line=130;
      Object \u03A3=$fix($opUnionY($opUnionY($opIntvlY('0','9'),$opIntvlY('a','z')),GCollections.asSet('(',')',' ')));
      $line=131;
      Object Out=$fix(GCollections.asSet('(',')','+','*','v','n'));
      $line=132;
      Object q_0=$fix("I");
      $line=133;
      Object F=$fix(GCollections.asSet("I"));
      $line=134;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,Out,q_0,F,new GMethod(LexerParser.class,"\u03B4"),new GMethod(LexerParser.class,"g"),new GMethod(LexerParser.class,"h")});
      if (true) break $try;
      $line=135;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=138;
      if ($bool($opEqualY(q,"Err"))) {
        $line=138;
        $result="Err";
        if (true) break $try;
      }
      else {
        $line=139;
        if ($opMembrY(\u03C3,GCollections.asSet('(',')',' '))) {
          $line=139;
          $result="I";
          if (true) break $try;
        }
        else {
          $line=140;
          if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'p'))) {
            $line=140;
            $result="p";
            if (true) break $try;
          }
          else {
            $line=141;
            if (($opEqualY(q,"I")&&$opEqualY(\u03C3,'t'))) {
              $line=141;
              $result="t";
              if (true) break $try;
            }
            else {
              $line=142;
              if (($opEqualY(q,"I")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                $line=142;
                $result="Num";
                if (true) break $try;
              }
              else {
                $line=143;
                if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('0','9')))) {
                  $line=143;
                  $result="Num";
                  if (true) break $try;
                }
                else {
                  $line=144;
                  if (($opEqualY(q,"Num")&&$opMembrY(\u03C3,$opIntvlY('a','z')))) {
                    $line=144;
                    $result="Err";
                    if (true) break $try;
                  }
                  else {
                    $line=145;
                    if (($opEqualY(q,"p")&&$opEqualY(\u03C3,'l'))) {
                      $line=145;
                      $result="pl";
                      if (true) break $try;
                    }
                    else {
                      $line=146;
                      if (($opEqualY(q,"pl")&&$opEqualY(\u03C3,'u'))) {
                        $line=146;
                        $result="plu";
                        if (true) break $try;
                      }
                      else {
                        $line=147;
                        if (($opEqualY(q,"plu")&&$opEqualY(\u03C3,'s'))) {
                          $line=147;
                          $result="plus";
                          if (true) break $try;
                        }
                        else {
                          $line=148;
                          if (($opEqualY(q,"t")&&$opEqualY(\u03C3,'i'))) {
                            $line=148;
                            $result="ti";
                            if (true) break $try;
                          }
                          else {
                            $line=149;
                            if (($opEqualY(q,"ti")&&$opEqualY(\u03C3,'m'))) {
                              $line=149;
                              $result="tim";
                              if (true) break $try;
                            }
                            else {
                              $line=150;
                              if (($opEqualY(q,"tim")&&$opEqualY(\u03C3,'e'))) {
                                $line=150;
                                $result="time";
                                if (true) break $try;
                              }
                              else {
                                $line=151;
                                if (($opEqualY(q,"time")&&$opEqualY(\u03C3,'s'))) {
                                  $line=151;
                                  $result="times";
                                  if (true) break $try;
                                }
                                else {
                                  $line=152;
                                  $result="Id";
                                  if (true) break $try;
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=154;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=159;
      $result="";
      if (true) break $try;
      $line=160;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=163;
      String s=null;
      s=$defaultValue(String.class);
      $line=164;
      s=$cast(String.class,$fix(""));
      $line=166;
      if ((!$opMembrY(q,GCollections.asSet("Err"))&&$opMembrY(\u03C3,GCollections.asSet('(',')',' ')))) {
        $line=168;
        if (!$opMembrY(\u03C3,GCollections.asSet(' '))) {
          $line=168;
          s=$cast(String.class,$fix($invokeMethod(String.class,"valueOf",true,null,new Object[]{\u03C3})));
        }
        $line=170;
        if ($opEqualY(q,"I")) {
          $line=170;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=171;
          if ($opEqualY(q,"plus")) {
            $line=171;
            $result=$opAdditY("+",s);
            if (true) break $try;
          }
          else {
            $line=172;
            if ($opEqualY(q,"times")) {
              $line=172;
              $result=$opAdditY("*",s);
              if (true) break $try;
            }
            else {
              $line=173;
              if ($opEqualY(q,"Num")) {
                $line=173;
                $result=$opAdditY("n",s);
                if (true) break $try;
              }
              else {
                $line=174;
                $result=$opAdditY("v",s);
                if (true) break $try;
              }
            }
          }
        }
      }
      else {
        $line=176;
        $result="";
        if (true) break $try;
      }
      $line=179;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,LexerParser.class,"h",$line);
    }
    return $result;
  }
}
