// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/P3.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class P3 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=4;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton[].class,$invokeMethod(P3.class,"createAutomaton",true,null,new Object[]{})));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P3.class,"main",$line);
    }
  }
  public static IPushdownAutomaton createAutomaton() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object Q=$fix(GCollections.asSet("R","V","B","a","m","D","T","x","C","O","z","s","e","W","U","t","f","p","E","n","F","R","L","r","k","N","i","h","l","w","d","r","I","g","u","o","c","v","P","K","Y"));
      $line=12;
      Object \u03A3=$fix(GCollections.asSet('R','V','B','a','m','D','T','x','C','O','z','s','e','W','U','t','f','p','E','n','F','R','L','r','k','N','i','h','l','w','d','r','I','g','u','o','c','v','P','K','$'));
      $line=16;
      Object \u0393=$fix(GCollections.asSet('N','B','a','n'));
      $line=17;
      Object q_0=$fix("I");
      $line=18;
      Object F=$fix(GCollections.asSet("I","E"));
      $line=20;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=21;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("I","R",$cast(java.lang.String.class,"R")),new Object[]{});
      $line=22;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("R","V",$cast(java.lang.String.class,"V")),new Object[]{});
      $line=23;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("V","N",$cast(java.lang.String.class,"N")),new Object[]{"N"});
      $line=24;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("N","N",$cast(java.lang.String.class,"N")),new Object[]{"N"});
      $line=25;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("N","B",$cast(java.lang.String.class,"B")),new Object[]{"B"});
      $line=26;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("R","B",$cast(java.lang.String.class,"B")),new Object[]{"B"});
      $line=28;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("B","m",$cast(java.lang.String.class,"m")),new Object[]{});
      $line=29;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("B","t",$cast(java.lang.String.class,"t")),new Object[]{});
      $line=30;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("B","f",$cast(java.lang.String.class,"f")),new Object[]{});
      $line=31;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("B","P",$cast(java.lang.String.class,"P")),new Object[]{});
      $line=32;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("B","p",$cast(java.lang.String.class,"p")),new Object[]{});
      $line=34;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("B","a",$cast(java.lang.String.class,"a")),new Object[]{"a"});
      $line=35;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("a","n",$cast(java.lang.String.class,"n")),new Object[]{"n"});
      $line=36;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("n","U",$cast(java.lang.String.class,"U")),new Object[]{"n"});
      $line=37;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("U","Y",$cast(java.lang.String.class,"N")),new Object[]{"a"});
      $line=38;
      $invokeMethod("push",((gold.structures.automaton.GPushdownAutomaton)M).delta("Y","a",$cast(java.lang.String.class,"a")),new Object[]{"a"});
      $line=40;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("Y","m",$cast(java.lang.String.class,"m")),new Object[]{});
      $line=41;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("m","Y",$cast(java.lang.String.class,"N")),new Object[]{});
      $line=42;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("m","Y",$cast(java.lang.String.class,"n")),new Object[]{});
      $line=43;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("Y","t",$cast(java.lang.String.class,"t")),new Object[]{});
      $line=44;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("t","Y",$cast(java.lang.String.class,"L")),new Object[]{});
      $line=45;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("t","Y",$cast(java.lang.String.class,"R")),new Object[]{});
      $line=46;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("t","Y",$cast(java.lang.String.class,"r")),new Object[]{});
      $line=47;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("Y","f",$cast(java.lang.String.class,"f")),new Object[]{});
      $line=48;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("f","Y",$cast(java.lang.String.class,"W")),new Object[]{});
      $line=49;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("f","Y",$cast(java.lang.String.class,"s")),new Object[]{});
      $line=50;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("f","Y",$cast(java.lang.String.class,"e")),new Object[]{});
      $line=51;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("f","Y",$cast(java.lang.String.class,"z")),new Object[]{});
      $line=52;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("Y","P",$cast(java.lang.String.class,"P")),new Object[]{});
      $line=53;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("P","Y",$cast(java.lang.String.class,"N")),new Object[]{});
      $line=54;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("P","Y",$cast(java.lang.String.class,"n")),new Object[]{});
      $line=55;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("n","o",$cast(java.lang.String.class,"o")),new Object[]{});
      $line=56;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("N","o",$cast(java.lang.String.class,"o")),new Object[]{});
      $line=57;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("o","O",$cast(java.lang.String.class,"O")),new Object[]{});
      $line=58;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("o","C",$cast(java.lang.String.class,"C")),new Object[]{});
      $line=59;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("Y","p",$cast(java.lang.String.class,"p")),new Object[]{});
      $line=60;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("p","Y",$cast(java.lang.String.class,"N")),new Object[]{});
      $line=61;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("p","Y",$cast(java.lang.String.class,"n")),new Object[]{});
      $line=62;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("n","T",$cast(java.lang.String.class,"T")),new Object[]{});
      $line=63;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("N","T",$cast(java.lang.String.class,"T")),new Object[]{});
      $line=64;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("T","F",$cast(java.lang.String.class,"F")),new Object[]{});
      $line=65;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("T","R",$cast(java.lang.String.class,"R")),new Object[]{});
      $line=66;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("T","L",$cast(java.lang.String.class,"L")),new Object[]{});
      $line=67;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta("T","K",$cast(java.lang.String.class,"K")),new Object[]{});
      $line=69;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("Y","E",$cast(java.lang.String.class,"E")),new Object[]{"B"});
      $line=70;
      $invokeMethod("pop",((gold.structures.automaton.GPushdownAutomaton)M).delta("E","E",$cast(java.lang.String.class,"")),new Object[]{"N"});
      $line=74;
      $result=M;
      if (true) break $try;
      $line=75;
      $rethrow(new RuntimeException("The function \"createAutomaton()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,P3.class,"createAutomaton",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
